/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    Breadcrumb: typeof import("./../components/Breadcrumb/index.vue")["default"];
    Dictionary: typeof import("./../components/Dictionary/index.vue")["default"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    GithubCorner: typeof import("./../components/GithubCorner/index.vue")["default"];
    Hamburger: typeof import("./../components/Hamburger/index.vue")["default"];
    HelloWorld: typeof import("./../components/HelloWorld.vue")["default"];
    IconSelect: typeof import("./../components/IconSelect/index.vue")["default"];
    IEpCheck: typeof import("~icons/ep/check")["default"];
    IEpClose: typeof import("~icons/ep/close")["default"];
    IEpInfoFilled: typeof import("~icons/ep/info-filled")["default"];
    IEpPicture: typeof import("~icons/ep/picture")["default"];
    IEpSetting: typeof import("~icons/ep/setting")["default"];
    IEpSuccessFilled: typeof import("~icons/ep/success-filled")["default"];
    IEpWarningFilled: typeof import("~icons/ep/warning-filled")["default"];
    IEpWarnTriangleFilled: typeof import("~icons/ep/warn-triangle-filled")["default"];
    LangSelect: typeof import("./../components/LangSelect/index.vue")["default"];
    MultiUpload: typeof import("./../components/Upload/MultiUpload.vue")["default"];
    Pagination: typeof import("./../components/Pagination/index.vue")["default"];
    RightPanel: typeof import("./../components/RightPanel/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SingleUpload: typeof import("./../components/Upload/SingleUpload.vue")["default"];
    SizeSelect: typeof import("./../components/SizeSelect/index.vue")["default"];
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"];
    WangEditor: typeof import("./../components/WangEditor/index.vue")["default"];
  }
}
