/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    AppMain: typeof import("./../layout/components/AppMain.vue")["default"];
    Breadcrumb: typeof import("./../components/Breadcrumb/index.vue")["default"];
    Dictionary: typeof import("./../components/Dictionary/index.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    GithubCorner: typeof import("./../components/GithubCorner/index.vue")["default"];
    Hamburger: typeof import("./../components/Hamburger/index.vue")["default"];
    IconSelect: typeof import("./../components/IconSelect/index.vue")["default"];
    IEpPicture: typeof import("~icons/ep/picture")["default"];
    Item: typeof import("./../layout/components/Sidebar/Item.vue")["default"];
    LangSelect: typeof import("./../components/LangSelect/index.vue")["default"];
    LeftMenu: typeof import("./../layout/components/Sidebar/LeftMenu.vue")["default"];
    Link: typeof import("./../layout/components/Sidebar/Link.vue")["default"];
    Logo: typeof import("./../layout/components/Sidebar/Logo.vue")["default"];
    MultiUpload: typeof import("./../components/Upload/MultiUpload.vue")["default"];
    NavBar: typeof import("./../layout/components/NavBar/index.vue")["default"];
    NavRight: typeof import("./../layout/components/NavBar/NavRight.vue")["default"];
    Pagination: typeof import("./../components/Pagination/index.vue")["default"];
    RightPanel: typeof import("./../components/RightPanel/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    ScrollPane: typeof import("./../layout/components/TagsView/ScrollPane.vue")["default"];
    Settings: typeof import("./../layout/components/Settings/index.vue")["default"];
    Sidebar: typeof import("./../layout/components/Sidebar/index.vue")["default"];
    SidebarItem: typeof import("./../layout/components/Sidebar/SidebarItem.vue")["default"];
    SingleUpload: typeof import("./../components/Upload/SingleUpload.vue")["default"];
    SizeSelect: typeof import("./../components/SizeSelect/index.vue")["default"];
    SvgIcon: typeof import("./../components/SvgIcon/index.vue")["default"];
    TagsView: typeof import("./../layout/components/TagsView/index.vue")["default"];
    TopMenu: typeof import("./../layout/components/Sidebar/TopMenu.vue")["default"];
    WangEditor: typeof import("./../components/WangEditor/index.vue")["default"];
  }
}
